-- MySQL Script generated by MySQL Workbench
-- Thu Oct 12 20:22:19 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema MagBuy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MagBuy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MagBuy` DEFAULT CHARACTER SET utf8mb4 ;
USE `MagBuy` ;

-- -----------------------------------------------------
-- Table `MagBuy`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MagBuy`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `enabled` INT(1) UNSIGNED NOT NULL,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  `mobile_phone` INT(11) NULL DEFAULT NULL,
  `image_url` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `last_login` DATE NULL DEFAULT NULL,
  `role` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `MagBuy`.`adresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MagBuy`.`adresses` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `full_adress` VARCHAR(255) NOT NULL,
  `is_personal` INT(1) UNSIGNED NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC),
  CONSTRAINT `adresses_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `MagBuy`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `MagBuy`.`supercategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MagBuy`.`supercategories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `MagBuy`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MagBuy`.`categories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `supercategory_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `categories_ibfk_1` (`supercategory_id` ASC),
  CONSTRAINT `categories_ibfk_1`
    FOREIGN KEY (`supercategory_id`)
    REFERENCES `MagBuy`.`supercategories` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `MagBuy`.`subcategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MagBuy`.`subcategories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `category_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `category_id` (`category_id` ASC),
  CONSTRAINT `subcategories_ibfk_1`
    FOREIGN KEY (`category_id`)
    REFERENCES `MagBuy`.`categories` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `MagBuy`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MagBuy`.`products` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `description` TEXT NOT NULL,
  `price` INT(11) UNSIGNED NULL DEFAULT NULL,
  `quantity` INT(11) UNSIGNED NOT NULL,
  `visible` TINYINT(1) UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `subcategory_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `subcategory_id` (`subcategory_id` ASC),
  CONSTRAINT `products_ibfk_1`
    FOREIGN KEY (`subcategory_id`)
    REFERENCES `MagBuy`.`subcategories` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `MagBuy`.`favourites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MagBuy`.`favourites` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `product_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `favourites_ibfk_1` (`user_id` ASC),
  INDEX `favourites_ibfk_2` (`product_id` ASC),
  CONSTRAINT `favourites_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `MagBuy`.`users` (`id`),
  CONSTRAINT `favourites_ibfk_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `MagBuy`.`products` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `MagBuy`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MagBuy`.`images` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `image_url` VARCHAR(255) NOT NULL DEFAULT '',
  `product_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `product_id` (`product_id` ASC),
  CONSTRAINT `images_ibfk_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `MagBuy`.`products` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `MagBuy`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MagBuy`.`orders` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `status` INT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC),
  CONSTRAINT `orders_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `MagBuy`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `MagBuy`.`order_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MagBuy`.`order_products` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT(11) NOT NULL,
  `product_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `order_id` (`order_id` ASC),
  INDEX `product_id` (`product_id` ASC),
  CONSTRAINT `order_products_ibfk_1`
    FOREIGN KEY (`order_id`)
    REFERENCES `MagBuy`.`orders` (`id`),
  CONSTRAINT `order_products_ibfk_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `MagBuy`.`products` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `MagBuy`.`promotions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MagBuy`.`promotions` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `percent` INT(11) UNSIGNED NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `product_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `product_id` (`product_id` ASC),
  CONSTRAINT `promotions_ibfk_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `MagBuy`.`products` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `MagBuy`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MagBuy`.`reviews` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `comment` VARCHAR(255) NOT NULL,
  `rating` INT(1) UNSIGNED NOT NULL,
  `user_id` INT(11) NOT NULL,
  `product_id` INT(11) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC),
  INDEX `product_id` (`product_id` ASC),
  CONSTRAINT `reviews_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `MagBuy`.`users` (`id`),
  CONSTRAINT `reviews_ibfk_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `MagBuy`.`products` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `MagBuy`.`subcat_specifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MagBuy`.`subcat_specifications` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL DEFAULT '',
  `subcategory_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `subcat_spec_ibfk_1` (`subcategory_id` ASC),
  CONSTRAINT `subcat_spec_ibfk_1`
    FOREIGN KEY (`subcategory_id`)
    REFERENCES `MagBuy`.`subcategories` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `MagBuy`.`subcat_specification_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MagBuy`.`subcat_specification_value` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(255) NOT NULL DEFAULT '',
  `subcat_spec_id` INT(11) NOT NULL,
  `product_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `subcat_spec_val_ibfk_1` (`subcat_spec_id` ASC),
  INDEX `subcat_spec_val_ibfk_2` (`product_id` ASC),
  CONSTRAINT `subcat_spec_val_ibfk_1`
    FOREIGN KEY (`subcat_spec_id`)
    REFERENCES `MagBuy`.`subcat_specifications` (`id`),
  CONSTRAINT `subcat_spec_val_ibfk_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `MagBuy`.`products` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
